let D=null,mode="monthly";const $=id=>document.getElementById(id),COL={open:"#ef5b5b",closed:"#28b487",monitoring:"#f4aa41"},PAL=["#6d5dfc","#28b487","#f4aa41","#ef5b5b","#36a2eb","#9b59b6","#16a085"];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const total=p=>(p.open||0)+(p.closed||0)+(p.monitoring||0);
async function load(force=false){try{const url=window.CTT_CONFIG?.API_URL;if(!url||url.includes("PASTE_"))throw new Error("Isi URL Web App pada config.js terlebih dahulu.");$("message").className="message";$("message").textContent="Mengambil data Google Sheet…";const r=await fetch(url+(url.includes("?")?"&":"?")+(force?"refresh=1":"t="+Date.now()),{redirect:"follow"});if(!r.ok)throw new Error("API merespons "+r.status);D=await r.json();if(D.error)throw new Error(D.error);init();$("message").className="message ok"}catch(e){$("message").className="message error";$("message").textContent="Data belum dapat dimuat: "+e.message}}
function active(){return (D[mode]||[]).filter(p=>(!$("from").value||p.dateKey>=$("from").value)&&(!$("to").value||p.dateKey<=$("to").value))}
function render(){const a=active(),s=a.reduce((x,p)=>({total:x.total+total(p),open:x.open+p.open,monitoring:x.monitoring+p.monitoring}),{total:0,open:0,monitoring:0}),g=a.filter(x=>x.mttr>0),avg=g.length?g.reduce((x,p)=>x+p.mttr,0)/g.length:0;$("kpis").innerHTML=`<article class="card"><span>Total TT</span><b>${s.total.toLocaleString("id-ID")}</b><small class="muted">Periode terpilih</small></article><article class="card"><span>Open</span><b>${s.open.toLocaleString("id-ID")}</b></article><article class="card"><span>Monitoring</span><b>${s.monitoring.toLocaleString("id-ID")}</b></article><article class="card"><span>Average Aging</span><b>${avg.toFixed(1)}d</b><small class="muted">Rata-rata antarperiode</small></article>`;drawTrend(a);drawRegion()}
function drawTrend(a){const W=1000,H=350,L=55,R=58,T=28,B=60,PW=W-L-R,PH=H-T-B,m=Math.max(...a.map(total),1),am=Math.max(...a.map(x=>x.mttr),1),st=PW/Math.max(a.length,1),bw=Math.min(32,st*.68),x=i=>L+i*st+st/2,y=v=>T+PH-v/m*PH,ay=v=>T+PH-v/am*PH;let q=`<svg viewBox="0 0 ${W} ${H}">`;[0,.25,.5,.75,1].forEach(t=>q+=`<line class="grid" x1="${L}" x2="${W-R}" y1="${T+PH*(1-t)}" y2="${T+PH*(1-t)}"/><text class="axis" x="${L-7}" y="${T+PH*(1-t)+3}" text-anchor="end">${Math.round(m*t)}</text><text class="axis" x="${W-R+7}" y="${T+PH*(1-t)+3}">${Math.round(am*t)}d</text>`);a.forEach((p,i)=>{const xx=x(i)-bw/2,y1=y(p.open),y2=y(p.open+p.closed),y3=y(total(p));q+=`<rect x="${xx}" y="${y1}" width="${bw}" height="${y(0)-y1}" fill="${COL.open}"/><rect x="${xx}" y="${y2}" width="${bw}" height="${y1-y2}" fill="${COL.closed}"/><rect x="${xx}" y="${y3}" width="${bw}" height="${y2-y3}" fill="${COL.monitoring}"><title>${esc(p.label)}: Total ${total(p)}</title></rect><text class="axis" x="${x(i)}" y="${Math.max(12,y3-5)}" text-anchor="middle">${total(p)}</text>`;if(i%Math.max(1,Math.ceil(a.length/10))===0)q+=`<text class="axis" x="${x(i)}" y="${H-24}" text-anchor="middle">${esc(p.label)}</text>`});q+=`<polyline fill="none" stroke="#6d5dfc" stroke-width="2.5" points="${a.map((p,i)=>x(i)+","+ay(p.mttr)).join(" ")}"/>`;a.forEach((p,i)=>q+=`<circle cx="${x(i)}" cy="${ay(p.mttr)}" r="3" fill="#fff" stroke="#6d5dfc"><title>${p.label}: ${p.mttr} hari</title></circle>`);$("trend").innerHTML=q+"</svg>";const last=a[a.length-1];$("trendDetail").innerHTML=last?`<b>${esc(last.label)}</b> Open ${last.open} · Closed ${last.closed} · Monitoring ${last.monitoring} · Total ${total(last)} · Avg Aging ${last.mttr} hari`:"Tidak ada data pada periode ini"}
function drawRegion(){const a=(D[mode==="monthly"?"monthlyRegion":"weeklyRegion"]||[]).filter(p=>(!$("from").value||p.dateKey>=$("from").value)&&(!$("to").value||p.dateKey<=$("to").value)),rs=[...new Set(a.flatMap(x=>Object.keys(x.regions)))],W=1000,H=320,L=55,R=25,T=28,B=55,PW=W-L-R,PH=H-T-B,m=Math.max(...a.flatMap(x=>rs.map(r=>x.regions[r]||0)),1),st=PW/Math.max(a.length-1,1),x=i=>L+i*st,y=v=>T+PH-v/m*PH;let q=`<div class="legend">${rs.map((r,i)=>`<span><i style="background:${PAL[i%PAL.length]}"></i>${esc(r)}</span>`).join("")}</div><svg viewBox="0 0 ${W} ${H}">`;[0,.25,.5,.75,1].forEach(t=>q+=`<line class="grid" x1="${L}" x2="${W-R}" y1="${T+PH*(1-t)}" y2="${T+PH*(1-t)}"/><text class="axis" x="${L-7}" y="${T+PH*(1-t)+3}" text-anchor="end">${Math.round(m*t)}</text>`);rs.forEach((r,i)=>q+=`<polyline fill="none" stroke="${PAL[i%PAL.length]}" stroke-width="2" points="${a.map((p,j)=>x(j)+","+y(p.regions[r]||0)).join(" ")}"/>`);a.forEach((p,i)=>{if(i%Math.max(1,Math.ceil(a.length/10))===0)q+=`<text class="axis" x="${x(i)}" y="${H-20}" text-anchor="middle">${esc(p.label)}</text>`});$("region").innerHTML=q+"</svg>"}
function bars(id,key,blank){const r=Object.entries(D.tickets.filter(t=>t.status==="Open").reduce((a,t)=>{const v=t[key]||(blank?"Normal TT":"");if(v)a[v]=(a[v]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]),m=Math.max(...r.map(x=>x[1]),1);$(id).innerHTML=r.map(([k,v])=>`<div class="row"><span title="${esc(k)}">${esc(k)}</span><div class="track"><div class="fill" style="width:${v/m*100}%"></div></div><b>${v}</b></div>`).join("")}
function options(id,key){const vals=[...new Set(D.tickets.map(t=>t[key]).filter(Boolean))].sort();$(id).innerHTML='<option value="">Semua</option>'+vals.map(v=>`<option>${esc(v)}</option>`).join("")}
function filtered(){const q=$("search").value.toLowerCase(),age=$("fAging").value;return D.tickets.filter(t=>(!q||t.siteId.toLowerCase().includes(q)||t.sitename.toLowerCase().includes(q))&&(!$("fCircle").value||t.circle===$("fCircle").value)&&(!$("fUrgent").value||t.urgent===$("fUrgent").value)&&(!$("fEsc").value||t.escalateTo===$("fEsc").value)&&(!$("fStatus").value||t.status===$("fStatus").value)&&(!$("fType").value||t.type===$("fType").value)&&(!age||(age==="lt3"&&t.aging<3)||(age==="gte3"&&t.aging>=3)||(age==="gt7"&&t.aging>7)||(age==="gt30"&&t.aging>30)))}
function table(){const r=filtered();$("count").textContent=r.length+" ticket";const keys=["tt","severity","openDate","type","siteId","sitename","region","summary","founding","partIssue","noRma","timePeriode","finalRca","rcaCategory","escalateTo","ttNoc","ttFso","aging","status","urgent","week"];$("tbody").innerHTML=r.map(t=>"<tr>"+keys.map(k=>`<td class="${["summary","founding","timePeriode","finalRca"].includes(k)?"long":""}">${esc(k==="aging"?Math.round(t[k]||0):t[k]||"-")}</td>`).join("")+"</tr>").join("")}
function init(){["Circle","Urgent","Esc","Status","Type"].forEach(k=>options("f"+k,{Circle:"circle",Urgent:"urgent",Esc:"escalateTo",Status:"status",Type:"type"}[k]));bars("esc","escalateTo");bars("rca","rcaCategory");bars("urgent","urgent",true);table();render();$("foot").textContent="Live update: "+new Date(D.refreshedAt).toLocaleString("id-ID")}
$("monthly").onclick=()=>{mode="monthly";$("monthly").classList.add("active");$("weekly").classList.remove("active");render()};$("weekly").onclick=()=>{mode="weekly";$("weekly").classList.add("active");$("monthly").classList.remove("active");render()};$("from").onchange=render;$("to").onchange=render;$("search").oninput=table;["fCircle","fUrgent","fEsc","fStatus","fType","fAging"].forEach(id=>$(id).onchange=table);$("refresh").onclick=()=>load(true);load();
